# Generated by Django 5.2 on 2025-04-30 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('type_encoded', models.IntegerField()),
                ('location_encoded', models.IntegerField()),
                ('time_encoded', models.IntegerField()),
                ('channel_encoded', models.IntegerField()),
                ('balance_before', models.FloatField()),
                ('balance_after', models.FloatField()),
                ('is_weekend', models.IntegerField()),
                ('client_age_group', models.IntegerField()),
                ('predicted_fraud', models.BooleanField()),
                ('confidence', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
